language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t sagarchuri/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sagarchuri/react-test npm test
    
after_success:
    - docker build -t sagarchuri/multi-client ./client
    - docker build -t sagarchuri/multi-nginx ./nginx
    - docker build -t sagarchuri/multi-server ./server
    - docker build -t sagarchuri/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sagarchuri/multi-client
    - docker push sagarchuri/multi-nginx
    - docker push sagarchuri/multi-server
    - docker push sagarchuri/multi-worker
    
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker-1"
  env: "MultiDocker1-env"
  bucket_name: "elasticbeanstalk-eu-west-2-553150330102"
  bucket_path: "multi-docker"
  on:
     branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    